#version: "3.8"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
    networks:
      - kirunaexplorer-network
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./Server/DB:/app/db
    networks:
      - kirunaexplorer-network
networks:
  kirunaexplorer-network:
    driver: bridge
